### ISSUE TITLE
Custom events are not delivered in production mode

### ISSUE THREAD

**Issue by alectogeek** [tenjin/flutter-sdk#2]
Hi!
Probably it is not related to this package at all, but maybe someone knows how to fix it: I integrated the package into my flutter app and it worked well in a sandbox mode (see https://prnt.sc/10ogeo7). But when I sent the app to production and launched ad campaigns it just didn't work. No events from SDK at all.

[Here is a link to repo showing how I use it](https://github.com/alectogeek/tenjin-sdk-implementation-example/blob/master/lib/main.dart)

Does anyone know what can cause the problem?

**Comment by thize** [comment]
![image](https://user-images.githubusercontent.com/10541221/112227169-f8b4e400-8c0d-11eb-852d-dffd56159f69.png)
try to find here, if it's empty, just wait

**Comment by alectogeek** [comment]
Yeah, I checked exactly that tab. 
I waited for quite a long time (more than a week already), but that didn't appear there. Trying to find a cause with the Tenjin support team. 
So you have never experienced such an issue, right?

**Comment by thize** [comment]
All my events work perfectly

**Comment by alectogeek** [comment]
Hm, what is going wrong then🤔

Thanks for your response!
