### ISSUE TITLE
SDK works great in debug mode, but doesn't send events in release mode

### ISSUE THREAD

**Issue by alectogeek** [tenjin/flutter-sdk#3]
I launch my app in debug and release mode and can see sending events to Live Test Device Data, but as soon as I restart my app in release mode, the events stop appearing on the Dashboard. 

Is there anything related to launching mode in the SDK that I forgot to take into account? 
It is really weird behavior, my app doesn't work in production.

Flutter doctor:
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.3 20D91 darwin-x64, locale en-DE)
    • Flutter version 1.22.6 at /Users/home/Programs/flutter
    • Framework revision 9b2d32b605 (9 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/home/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.
```

**Comment by thize** [comment]
Your application has Proguard configured correctly?

https://github.com/thize/flutter_tenjin_sdk#proguard-settings

**Comment by alectogeek** [comment]
Yeah, looks like that was the problem!
The tricky moment was that it worked well even in release launches on the device, so I didn't pay attention to that and I could find the Proguard configuration in the example of the library.
